# Use the official OpenJDK image as the base image
FROM openjdk:11-jre-slim

# Set the working directory in the container
WORKDIR /app

# Copy the WireMock standalone JAR and custom extension JAR to the container
COPY wiremock-standalone-3.3.1.jar /app/wiremock-standalone.jar
COPY WiremockDocker.main.jar /app/WiremockDocker.main.jar

# Set the environment variable for the port
ENV WM_PORT=9999

# Expose the port defined in the environment variable
EXPOSE $WM_PORT

# Command to run WireMock with the specified port and extension
RUN java -cp "wiremock-standalone.jar:WiremockDocker.main.jar" wiremock.Run --port $WM_PORT --extensions com.wiremockExt.JsonFileResponseValidator
